### PR TITLE
Add playbook to test setting up multiple users

### PR DESCRIPTION
**Pull request by milanmlft**
- Add `configure/playbooks/test-multiple_xnat_users.yml` and the `configure/run_tests.sh` driver script
- Set up a desired number (default: 4) of test users on the XNAT server and upload a single subject dataset for each of them
- Run tasks concurrently - using Ansible's `async` - to test if infrastructure can handle simultaneous data uploads
- Decrease reserved memory for FastSurfer Docker containers to allow more simultaneous runs

Related to #71.

### CODE REVIEW

**Review by p-j-smith — CHANGES_REQUESTED** [review]
nice! I haven't tried it out, but did it manage okay uploading files with multiple users?

Would it be possible to integrate adding multiple users into the existing `setup_xnat_project` role? It looks like there's quite a bit of overlap between them. Perhaps `n_users` could default to 1, in which case the entire dataset would be uploaded, and then if `n_users` > 1 only the first subject is uploaded (as you've done here). Or would all this add a lot of complexity?

Also, I think it would be good to set the value of `n_users` in the `group_vars` (possibly with the [existing `xnat_project` variables](https://github.com/UCL-MIRSG/xnat-aws/blob/e0715d5fb942ad11afc048f0f9442000a02ee9ee/configure/group_vars/web/vars/xnat_project.yml#L2C7-L2C7)?) rather than the playbooks and shell script, just to minimise the number of places to look for setting variables

**Comment by milanmlft** [comment]
Yeah I thought about that, but I reckoned it would be better to have a separate playbook to use just for testing. I wanted something that was mostly independent from the rest of the setup. But it's true that there is quite some code duplication now. I'll think about how to further reduce that.

**Comment by p-j-smith** [comment]
> Yeah I thought about that, but I reckoned it would be better to have a separate playbook to use just for testing. 

Yeah that's probably a good idea. You could keep both playbooks - `setup_xnat_project.yml` and `test-multiple_xnat_users.yml` - with the only difference being that `setup_xnat_project.yml` uses the default `n_users: 1` and `test-multiple_xnat_users.yml` overrides the default to 4 in the same way you're already doing

**Review by p-j-smith — APPROVED** [review]
I think it's good to merge this in for now and if there's time later then come back to removing the duplicated code

**Pull request merged**
