### PR TITLE
Update FastSurfer Docker containers

### LINKED ISSUE #70: `pydeface` missing when converting NIFTI to 256 conformed MGZ file
When running the `Converts NIFTI to 256 conformed MGZ file` command, as part of the IDEAS workshop (see #44), we run into the following error:

```
/fastsurfer/nii_to_mgz.sh: line 27: pydeface: command not found
Deface failed
```

What is confusing is that in the workshop, the defacing is performed _after_ the first run of FastSurfer (after which FastSurfer is re-run to see the impact on the results). So there is no need to have `pydeface` when we just want to convert the NIFTI files to MGZ, I think?

### PR DESCRIPTION
**Pull request by milanmlft**
- Use the new Docker containers from HealthBioscienceIDEAS/MedICSS-Project-Repro-Pipelines#24 to run the FastSurfer commands
- Add separate commands for running FastSurfer with or without GPU support
- Use `t3.large` for the Container Service instance to handle FastSurfer

Fixes #70

### CODE REVIEW

**Comment by milanmlft** [comment]
Still need to test whether this runs successfully.

**Comment by p-j-smith** [comment]
> Still need to test whether this runs successfully.

did you have any luck getting the surface reconstruction to run?

**Comment by milanmlft** [comment]
> > Still need to test whether this runs successfully.
> 
> did you have any luck getting the surface reconstruction to run?

Re-running it now an a different image. Seems to be running for longer already than previously, so 🤞

**Review by milanmlft — COMMENTED** [review]
Had to change the `limit-cpu` value to 2 to get the containers to run on the current setup. We might consider using one of the [Compute-optimized EC2 instances](https://aws.amazon.com/ec2/instance-types/c5/) for the Container Service though to reduce runtimes. Or completely switch to GPU (#51).

**Comment by milanmlft** [comment]
The FastSurfer analysis runs successfully now but there is still an issue with the output files. For some reason, XNAT fails to upload them (see screenshot), though they are present in the correct path (manually confirmed by `ssh`ing into the EC2 instance).
image

I'm going to merge this now but I'll create another issue for this problem: #74.

**Pull request merged**
